const node_path = 'C:\\Users\\povica\\AppData\\Roaming\\npm\\node_modules';
const fetch = require(node_path + '\\' + 'node-fetch');

console.log('Starting test');

let requests = [];
const words = [
  'a',
  'aa',
  'aaa',
  'aah',
  'aahed',
  'aahing',
  'aahs',
  'aal',
  'aalii',
  'aaliis',
  'aals',
  'aam',
  'aardvark',
  'aardvarks',
  'aardwolf',
  'aardwolves',
  'aargh',
  'aaron',
  'aaronic',
  'aarrgh',
  'aarrghh',
  'aas',
  'aasvogel',
  'aasvogels',
  'ab',
  'aba',
  'abac',
  'abaca',
  'abacas',
  'abacate',
  'abacaxi',
  'abacay',
  'abaci',
  'abacinate',
  'abacination',
  'abacisci',
  'abaciscus',
  'abacist',
  'aback',
  'abacli',
  'abacot',
  'abacterial',
  'abactinal',
  'abactinally',
  'abaction',
  'abactor',
  'abaculi',
  'abaculus',
  'abacus',
  'abacuses',
  'abada',
  'abaddon',
  'abadejo',
  'abadengo',
  'abadia',
  'abaff',
  'abaft',
  'abaisance',
  'abaised',
  'abaiser',
  'abaisse',
  'abaissed',
  'abaka',
  'abakas',
  'abalation',
  'abalienate',
  'abalienated',
  'abalienating',
  'abalienation',
  'abalone',
  'abalones',
  'abamp',
  'abampere',
  'abamperes',
  'abamps',
  'aband',
  'abandon',
  'abandonable',
  'abandoned',
  'abandonedly',
  'abandonee',
  'abandoner',
  'abandoners',
  'abandoning',
  'abandonment',
  'abandonments',
  'abandons',
  'abandum',
  'abanet',
  'abanga',
  'abannition',
  'abapical',
  'abaptiston',
  'abaptistum',
  'abarthrosis',
  'abarticular',
  'abarticulation',
  'abas',
  'abase',
  'abased',
  'abasedly',
  'abasedness',
  'abasement',
  'abasements',
  'abaser',
  'abasers',
  'abases',
  'abash',
  'abashed',
  'abashedly',
  'abashedness',
  'abashes',
  'abashing',
  'abashless',
  'abashlessly',
  'abashment',
  'abashments',
  'abasia',
  'abasias',
  'abasic',
  'abasing',
  'abasio',
  'abask',
  'abassi',
  'abastard',
  'abastardize',
  'abastral',
  'abatable',
  'abatage',
  'abate',
  'abated',
  'abatement',
  'abatements',
  'abater',
  'abaters',
  'abates',
  'abatic',
  'abating',
  'abatis',
  'abatised',
  'abatises',
  'abatjour',
  'abatjours',
  'abaton',
  'abator',
  'abators',
  'abattage',
  'abattis',
  'abattised',
  'abattises',
  'abattoir',
  'abattoirs',
  'abattu',
  'abattue',
  'abature',
  'abaue',
  'abave',
  'abaxial',
  'abaxile',
  'abay',
  'abayah',
  'abaze',
  'abb',
  'abba',
  'abbacies',
  'abbacomes',
  'abbacy',
  'abbandono',
  'abbas',
  'abbasi',
  'abbasid',
  'abbassi',
  'abbate',
  'abbatial',
  'abbatical',
  'abbatie',
  'abbaye',
  'abbe',
  'abbes',
  'abbess',
  'abbesses',
  'abbest',
  'abbevillian',
  'abbey',
  'abbeys',
  'abbeystead',
  'abbeystede',
  'abboccato',
  'abbogada',
  'abbot',
  'abbotcies',
  'abbotcy',
  'abbotnullius',
  'abbotric',
  'abbots',
  'abbotship',
  'abbotships',
  'abbott',
  'abbozzo',
  'abbr',
  'nonpreparatory',
  'nonpreparedness',
  'nonprepayment',
  'nonprepositional',
  'nonprepositionally',
  'nonpresbyter',
  'nonprescient',
  'nonpresciently',
  'nonprescribed',
  'nonprescriber',
  'nonprescription',
  'nonprescriptive',
  'nonpresence',
  'nonpresentability',
  'nonpresentable',
  'nonpresentableness',
  'nonpresentably',
  'nonpresentation',
  'nonpresentational',
  'nonpreservable',
  'nonpreservation',
  'nonpreservative',
  'nonpresidential',
  'nonpress',
  'nonpressing',
  'nonpressure',
  'nonpresumptive',
  'nonpresumptively',
  'nonprevalence',
  'nonprevalent',
  'nonprevalently',
  'nonpreventable',
  'nonpreventible',
  'nonprevention',
  'nonpreventive',
  'nonpreventively',
  'nonpreventiveness',
  'nonpriestly',
  'nonprimitive',
  'nonprimitively',
  'nonprimitiveness',
  'nonprincipiate',
  'nonprincipled',
  'nonprintable',
  'nonprinting',
  'nonprivileged',
  'nonprivities',
  'nonprivity',
  'nonprobabilities',
  'nonprobability',
  'nonprobable',
  'nonprobably',
  'nonprobation',
  'nonprobative',
  'nonprobatory',
  'nonproblematic',
  'nonproblematical',
  'nonproblematically',
  'nonprocedural',
  'nonprocedurally',
  'nonprocessional',
  'nonprocreation',
  'nonprocreative',
  'nonprocurable',
  'nonprocuration',
  'nonprocurement',
  'nonproducer',
  'nonproducible',
  'nonproducing',
  'nonproduction',
  'nonproductive',
  'nonproductively',
  'nonproductiveness',
  'nonproductivity',
  'nonprofane',
  'nonprofanely',
  'nonprofaneness',
  'nonprofanities',
  'nonprofanity',
  'nonprofessed',
  'nonprofession',
  'nonprofessional',
  'nonprofessionalism',
  'nonprofessionally',
  'nonprofessorial',
  'nonprofessorially',
  'nonproficience',
  'nonproficiency',
  'nonproficient',
  'nonprofit',
  'nonprofitability',
  'nonprofitable',
  'nonprofitablely',
  'nonprofitableness',
  'nonprofiteering',
  'nonprognostication',
  'nonprognosticative',
  'nonprogrammable',
  'nonprogrammer',
  'nonprogressive',
  'nonprogressively',
  'nonprogressiveness',
  'nonprohibitable',
  'nonprohibition',
  'nonprohibitive',
  'nonprohibitively',
  'nonprohibitorily',
  'nonprohibitory',
  'nonprojecting',
  'nonprojection',
  'nonprojective',
  'nonprojectively',
  'nonproletarian',
  'nonproletariat',
  'nonproliferation',
  'nonproliferous',
  'nonprolific',
  'nonprolificacy',
  'nonprolifically',
  'nonprolificness',
  'nonprolifiness',
  'nonprolix',
  'nonprolixity',
  'nonprolixly',
  'nonprolixness',
  'nonprolongation',
  'nonprominence',
  'nonprominent',
  'nonprominently',
  'nonpromiscuous',
  'nonpromiscuously',
  'nonpromiscuousness',
  'nonpromissory',
  'nonpromotion',
  'nonpromotive',
  'nonpromulgation',
  'nonpronunciation',
  'nonpropagable',
  'nonpropagandist',
  'nonpropagandistic',
  'nonpropagation',
  'nonpropagative',
  'nonpropellent',
  'nonprophetic',
  'nonprophetical',
  'nonprophetically',
  'nonpropitiable',
  'nonpropitiation',
  'nonpropitiative',
  'nonproportionable',
  'nonproportional',
  'nonproportionally',
  'nonproportionate',
  'nonproportionately',
  'nonproportionateness',
  'nonproportioned',
  'nonproprietaries',
  'nonproprietary',
  'nonproprietor',
  'nonpropriety',
  'nonprorogation',
  'nonpros',
  'nonprosaic',
  'nonprosaically',
  'nonprosaicness',
  'nonproscription',
  'nonproscriptive',
  'nonproscriptively',
  'nonprosecution',
  'nonprospect',
  'nonprosperity',
  'nonprosperous',
  'nonprosperously',
  'nonprosperousness',
  'nonprossed',
  'nonprosses',
  'nonprossing',
  'nonprotecting',
  'nonprotection',
  'nonprotective',
  'nonprotectively',
  'nonproteid',
  'nonprotein',
  'nonproteinaceous',
  'nonprotestation',
  'nonprotesting',
  'nonprotractile',
  'nonprotractility',
  'nonprotraction',
  'nonprotrusion',
  'nonprotrusive',
  'nonprotrusively',
  'nonprotrusiveness',
  'nonprotuberance',
  'nonprotuberancies',
  'nonprotuberancy',
  'nonprotuberant',
  'nonprotuberantly',
  'nonprovable',
   'nonproven',
//   'nonprovided',
//   'nonprovident',
//   'nonprovidential',
//   'nonprovidentially',
//   'nonprovidently',
//   'nonprovider',
//   'nonprovincial',
//   'nonprovincially',
//   'nonprovisional',
//   'nonprovisionally',
//   'nonprovisionary',
//   'nonprovocation',
//   'nonprovocative',
//   'nonprovocatively',
//   'nonprovocativeness',
//   'nonproximity',
//   'nonprudence',
//   'nonprudent',
//   'nonprudential',
//   'nonprudentially',
//   'nonprudently',
//   'nonpsychiatric',
//   'nonpsychic',
//   'nonpsychical',
//   'nonpsychically',
//   'nonpsychoanalytic',
//   'nonpsychoanalytical',
//   'nonpsychoanalytically',
//   'nonpsychologic',
//   'nonpsychological',
//   'nonpsychologically',
//   'nonpsychopathic',
//   'nonpsychopathically',
//   'nonpsychotic',
//   'nonpublic',
//   'nonpublication',
//   'nonpublicity',
//   'nonpublishable',
//   'nonpueblo',
//   'nonpuerile',
//   'nonpuerilely',
//   'nonpuerilities',
//   'nonpuerility',
//   'nonpulmonary',
//   'nonpulsating',
//   'nonpulsation',
//   'nonpulsative',
//   'nonpumpable',
//   'nonpunctual',
//   'nonpunctually',
//   'nonpunctualness',
//   'nonpunctuating',
//   'nonpunctuation',
//   'nonpuncturable',
//   'nonpungency',
//   'nonpungent',
//   'nonpungently',
//   'nonpunishable',
//   'nonpunishing',
//   'nonpunishment',
//   'nonpunitive',
//   'nonpunitory',
//   'nonpurchasability',
//   'nonpurchasable',
//   'nonpurchase',
//   'nonpurchaser',
//   'nonpurgation',
//   'nonpurgative',
//   'nonpurgatively',
//   'nonpurgatorial',
//   'nonpurification',
//   'nonpurifying',
//   'nonpuristic',
//   'nonpurposive',
//   'nonpurposively',
//   'nonpurposiveness',
//   'nonpursuance',
//   'nonpursuant',
//   'nonpursuantly',
//   'nonpursuit',
//   'nonpurulence',
//   'nonpurulent',
//   'nonpurulently',
//   'nonpurveyance',
//   'nonputrescence',
//   'nonputrescent',
//   'nonputrescible',
//   'nonputting',
//   'nonpyogenic',
//   'nonpyritiferous',
//   'nonqualification',
//   'nonqualifying',
//   'nonqualitative',
//   'nonqualitatively',
//   'nonqualities',
//   'nonquality',
//   'nonquantitative',
//   'nonquantitatively',
//   'nonquantitativeness',
//   'nonquota',
//   'nonrabbinical',
//   'nonracial',
//   'nonracially',
//   'nonradiable',
//   'nonradiance',
//   'nonradiancy',
//   'nonradiant',
//   'nonradiantly',
//   'nonradiating',
//   'nonradiation',
//   'nonradiative',
//   'nonradical',
//   'nonradically',
//   'nonradicalness',
//   'nonradicness',
//   'nonradioactive',
//   'nonrailroader',
//   'nonraisable',
//   'nonraiseable',
//   'nonraised',
//   'nonrandom',
//   'nonrandomly',
//   'nonrandomness',
//   'nonranging',
//   'nonrapport',
//   'nonratability',
//   'nonratable',
//   'nonratableness',
//   'nonratably',
//   'nonrateability',
//   'nonrateable',
//   'nonrateableness',
//   'nonrateably',
//   'nonrated',
//   'nonratification',
//   'nonratifying',
//   'nonrational',
//   'nonrationalism',
//   'nonrationalist',
//   'nonrationalistic',
//   'nonrationalistical',
//   'nonrationalistically',
//   'nonrationality',
//   'nonrationalization',
//   'nonrationalized',
//   'nonrationally',
//   'nonrationalness',
//   'nonrayed',
//   'nonreaction',
//   'nonreactionaries',
//   'nonreactionary',
//   'nonreactive',
//   'nonreactor',
//   'nonreadability',
//   'nonreadable',
//   'nonreadableness',
//   'nonreadably',
//   'nonreader',
//   'nonreaders',
//   'nonreading',
//   'nonrealism',
//   'nonrealist',
//   'nonrealistic',
//   'nonrealistically',
//   'nonrealities',
//   'nonreality',
//   'nonrealizable',
//   'nonrealization',
//   'nonrealizing',
//   'nonreasonability',
//   'nonreasonable',
//   'nonreasonableness',
//   'nonreasonably',
//   'nonreasoner',
//   'nonreasoning',
//   'nonrebel',
//   'nonrebellion',
//   'nonrebellious',
//   'nonrebelliously',
//   'nonrebelliousness',
//   'nonrecalcitrance',
//   'nonrecalcitrancy',
//   'nonrecalcitrant',
//   'nonreceipt',
//   'nonreceivable',
//   'nonreceiving',
//   'nonrecent',
//   'nonreception',
//   'nonreceptive',
//   'nonreceptively',
//   'nonreceptiveness',
//   'nonreceptivity',
//   'nonrecess',
//   'nonrecession',
//   'nonrecessive',
//   'nonrecipience',
//   'nonrecipiency',
//   'nonrecipient',
//   'nonreciprocal',
//   'nonreciprocally',
//   'nonreciprocals',
//   'nonreciprocating',
//   'nonreciprocity',
//   'nonrecision',
//   'nonrecital',
//   'nonrecitation',
//   'nonrecitative',
//   'nonreclaimable',
//   'nonreclamation',
//   'nonrecluse',
//   'nonreclusive',
//   'nonrecognition',
//   'nonrecognized',
//   'nonrecoil',
//   'nonrecoiling',
//   'nonrecollection',
//   'nonrecollective',
//   'nonrecombinant',
//   'nonrecommendation',
//   'nonreconcilability',
//   'nonreconcilable',
//   'nonreconcilableness',
//   'nonreconcilably',
//   'nonreconciliation',
//   'nonrecourse',
//   'nonrecoverable',
//   'nonrecovery',
//   'nonrectangular',
//   'nonrectangularity',
//   'nonrectangularly',
//   'nonrectifiable',
//   'nonrectified',
//   'nonrecuperatiness',
//   'nonrecuperation',
//   'nonrecuperative',
//   'nonrecuperativeness',
//   'nonrecuperatory',
//   'nonrecurent',
//   'nonrecurently',
//   'nonrecurrent',
//   'nonrecurring',
//   'nonredeemable',
//   'nonredemptible',
//   'nonredemption',
//   'nonredemptive',
//   'nonredressing',
//   'nonreduced',
//   'nonreducibility',
//   'nonreducible',
//   'nonreducibly',
//   'nonreducing',
//   'nonreduction',
//   'nonreductional',
//   'nonreductive',
//   'nonreference',
//   'nonrefillable',
//   'nonrefined',
//   'nonrefinement',
//   'nonreflected',
//   'nonreflecting',
//   'nonreflection',
//   'nonreflective',
//   'nonreflectively',
//   'nonreflectiveness',
//   'nonreflector',
//   'nonreformation',
//   'nonreformational',
//   'nonrefracting',
//   'nonrefraction',
//   'nonrefractional',
//   'nonrefractive',
//   'nonrefractively',
//   'nonrefractiveness',
//   'nonrefrigerant',
//   'nonrefueling',
//   'nonrefuelling',
//   'nonrefundable',
//   'nonrefutal',
//   'nonrefutation',
//   'nonregardance',
//   'nonregarding',
//   'nonregenerate',
//   'nonregenerating',
//   'nonregeneration',
//   'nonregenerative',
//   'nonregeneratively',
//   'nonregent',
//   'nonregimental',
//   'nonregimented',
//   'nonregistered',
//   'nonregistrability',
//   'nonregistrable',
//   'nonregistration',
//   'nonregression',
//   'nonregressive',
//   'nonregressively',
//   'nonregulation',
//   'nonregulative',
//   'nonregulatory',
//   'nonrehabilitation',
//   'nonreigning',
//   'nonreimbursement',
//   'nonreinforcement',
//   'nonreinstatement',
];

for (let i = 0; i < words.length; i++) {
  requests.push(fetch(`http://localhost:8000/api/v1/similar?word=${words[i]}`));
}

Promise.all(requests).then(() => {
  console.log('Finished');
  fetch('http://localhost:8000/api/v1/stats')
    .then(res => res.json())
    .then(json => console.log(json));
});
