tags:
- name: similar
  description: Similar words API

- name: stats
  description: Similar words API usage statistics

paths:
  /api/v1/similar:
    get:
      tags:
      - similar
      summary: Find similar words
      parameters:
        - in: query
          name: word
          schema:
            type: string
          required: true
          description: Word to use for similar lookup
      responses:
        200:
          description: Similar words JSON object
        400:
          description: Bad query input
        500:
          description: 'Server Error'

  /api/v1/stats:
    get:
      tags:
      - stats
      summary: Display similar words API usage statistics
      responses:
        200:
          description: Statistics JSON object
        500:
          description: Server Error